### ISSUE TITLE
Granting access to data and codes?

### ISSUE THREAD

**Issue by Nestak2** [tynski/AirPolutionPrediction#1]
Hi and thanks for publishing your project! I am working in my free time also on air pollution prediction and would like to access your data, I hope their public! When I click on the provided links in the repository I get redirected to an access request to a Google Drive. I've made the requests, but I just wanted to remind you here, too, in case you miss the email. Cheers

**Comment by tynski** [comment]
Thank you for raising the issue. I moved files to Dropbox. In case of any problems please let me know.
